name = "CamiDiff"
uuid = "2453a446-82e3-4664-a8e3-5851c117fba8"
authors = ["Jook Walraven <69215586+walra356@users.noreply.github.com> and contributors"]
version = "0.1.0" 

[deps]
CamiMath = "d302b3f7-c8ae-418d-9fc2-2c0a42bddda0"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
DocumenterInterLinks = "d12716ef-a0f6-4df4-a9f1-a5a34e75c656"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[compat]
CamiMath = "0.1.23"
Documenter = "1.14"
DocumenterInterLinks = "1.1"
julia = "1.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
